name: Deploy VPC and EC2 with AWS Secrets Manager

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Retrieve AWS Credentials from Secrets Manager
        id: get-secrets
        run: |
          aws secretsmanager get-secret-value --secret-id github/aws-creds --query 'SecretString' --output text --region us-east-1 > aws_creds.json
          echo "AWS_ACCESS_KEY_ID=$(jq -r .AWS_ACCESS_KEY_ID aws_creds.json)" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(jq -r .AWS_SECRET_ACCESS_KEY aws_creds.json)" >> $GITHUB_ENV


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve -var "aws_access_key=${AWS_ACCESS_KEY_ID}" -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}"
        working-directory: terraform
